[[MLX_C]]
arch = "aarch64"
git-tree-sha1 = "ab976240695d868415635f0d9c2bc6095f4edbaf"
os = "macos"

    [[MLX_C.download]]
    sha256 = "51797edb843796325a972ae67a7e379e2412ddc3c25054a4a920489cbb65f0bb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-apple-darwin.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f06d8de59221ad697b2cd243c239906065e10df"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d1f2352214ade6d7195cbd4df0131e292a368abf0e7e4f4d43eea9cb94199ffb"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51cdcf2a58851e79d9886d68f7dd8547882561dd"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "2597545c23fb95b4ee739bf916ab65dc42ef1156d53a0f489b0fced13475b916"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b552400da2598367c16e69c53bd9e077d4e707fd"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "87defbcbf1c701142a1ab028d3d72baf4a400ae2b77ceb1ad8567cd16f34986e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abbc8dfd14615c0036bee70580e621155403489d"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "da0a3700407c6774519401bcc262e382ca4edc3fcd050d0920f6c7b90fe77510"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "aarch64"
git-tree-sha1 = "aef6d497bee94cacda5a3484e164b500d351396c"
os = "freebsd"

    [[MLX_C.download]]
    sha256 = "f3dd9e20bc15f3d6978ba1b084331f70e838f321fe3349071a5dd5afdfceebec"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.aarch64-unknown-freebsd.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "184ce6845fd4717037d7b8b0da41b8bfb8437b29"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "c401f84958abe79f32c77771eb202e0371d3b1acc7ef451589cef47e2488c6e8"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b9358b025127fd1bd8a00d95710e6351e90e571"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "a885cec05866cf00976f3a2d895042ec5a6492a622b55ebd3baba568c69914ac"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e0b621654782aa3acddc9c4d0b5a13c832856aa"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d34dd11d0ea517dfa60a6c4283f2c50c5a89f4ce61aa3cab8198523aa6228bad"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7555e9673b14ad3af997466f099d9321e7ee80f6"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "c0a7c6810c32ef52df01d2af42f4665254c88aa88ae657d3dd66419095188057"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb2ea0fb3e7e48951d67ea0227f7ac3328b70f1c"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d6554390b27d138a6c4729dca79ee283d14ac3c4e50c6e864155c9905747de2e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f99b738c75c2e713c64917a8346ababc1a0208af"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "93f1b03113ee8ba994b4364250b50c81ace6eea5a47b84b8f6b7505a583e4003"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9ffd30a4d2e45a5a0dad517a5ad56ac67e2580"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "2a906c8d60042fcb7243464c5cab2b9651b902690f97a606f9c1d6b0aa0c184b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d813a8e34d77657338fc78acad0ecb0b2248f0b9"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "632d8b7e7238004abd68dbcb975b39f5faea8f900e7712b9e4623c9a5c7975cc"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8fa24a3677d5a3cee61178b3a77a3da6827e342"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d24432f59e22170f3250e338c2e0c45c5636d52ce4052063d3648ee90f03ac6b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1ab1cfb85f7e2cc712110af80d3f245abd4a2dc"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "27d12524e9a623d89fba93456db2e740a5ec08fbc708cec496eb22441141e8e0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "975356e433ea3121aa37ce999890c89e880bc828"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "552e61613a6a3e8bfeaadc75f652bbfb6031854c7d262f3da3d84b7cbba1f79d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47709336dad8a6c20a5fa42de45a5de14c48553"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "430187483752b31898e5bc52bdb28b7a45eef89b4625ad5e6b4cfaa0476ab9e7"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e71fd3e1409a6ba9bbfc86d3bb8c9b0b842f367"
os = "windows"

    [[MLX_C.download]]
    sha256 = "9c58d9c188b45ffef4da5fe428809ff2e1d153ad06cd8e7f0fce5db5db34e211"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac35cf1493b94af259d01e3e0ece5bb9dfd38ded"
os = "windows"

    [[MLX_C.download]]
    sha256 = "bfb42e0aaaeadacd173b98e27ac4d147d67982f3e5434890920c312ab23e7c33"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLX_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65a44f692e1f7d8a73b813f12008931341769ad1"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "7eb245334b5390d88d1e7e95c4e66b32d09381da969ffdb5e014e905769076a9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbf65c22d0b57baa588c9bd298888215229ca9c8"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "c83b3039d67ba55bef31c0bb59c0f9d344cfa46f61486f6dfb93560f5f1b02ed"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6100a6f3e5693cd19a8b393667d96cc1626939e6"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "f394912a5fdd9a4bc921b8ac4622611c2f2f3ee06e500d4ef0fbbdc9f4121684"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "272ec18e95447dcd8913055fb0a7ea87485d818d"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "7aa5fdf78a35e83d27048bd131760244edb62bd5e9fbe747c8d6f228b579480e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
git-tree-sha1 = "0f6cc8db6fa134bed1dadef1f31d6045339edac6"
os = "macos"

    [[MLX_C.download]]
    sha256 = "5363b26ee2e2b9affd8734f567254b985eb85572e32f6d10562d02bfee883338"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-apple-darwin.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4862134cd47d44441967b61dd21e37584c6baf20"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "2541c54eb7d103466f3bdbbc9a5ef56e53986a8b700564ca2b716b0a7860f673"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8048f9535da07bc32b0c29bc2ad1b1d46e618d4a"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "dccfef42bd87adf01362516fb7cf9dba898ff541b75a3583f0e8307dbd552452"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64ce1b70878331088a5df9d7258b835cd4bd94d6"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "5f098c6d4ba154ba285577a8f9dc01515fa70420d610053fdce52c7467468445"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65e7859579013453b88c651a6d06c39b56263c5e"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "e461ee7ec54c3198d856354bcd25faf3aced2205159d1b0ee2668dddd19d32ad"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
git-tree-sha1 = "7e579494b53b29dc1404c1c500152e98a836360e"
os = "freebsd"

    [[MLX_C.download]]
    sha256 = "a6bc9fc24e80efb9056d83111814a265eca065aaaf71e5e98ac1f93b5280237b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "953535c7778307438ed3e6394e861fcc1de607d1"
os = "windows"

    [[MLX_C.download]]
    sha256 = "87330768a3554141a4bee8468d84dedf6341e739279546ca298bd7aaf715abd1"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5229b834335e3784682cbf2fe11cd7c00591f4c1"
os = "windows"

    [[MLX_C.download]]
    sha256 = "8b20612ff772fd845c3ac6d95142996ce46e9794591c07d8dc38d05b7e4b7120"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.1.1+0/MLX_C.v0.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
