[[MLX_C]]
arch = "aarch64"
git-tree-sha1 = "dd4a88c41b855400c6bd803137bed9d7700d1486"
os = "macos"

    [[MLX_C.download]]
    sha256 = "62466d299816a184208d30c0650a2eac98b4d4430bbd30629e6ecdea2f6de5c0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-apple-darwin.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b2670dc98503b31ae4c50473a811ba3aaafe6b8"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "97741ab498203c8688d2f5247710a44bdad0b91fb1285faf4fbb121146fd1d14"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b00338577adb17a8b8c32cb4a55b2245b67750c"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "589cf58e5331dcf31c07ac7bfc03eb45957117a2a7f94662d71afeb6bfc49483"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d475c53a015a55f658f0483f3bb6bc998559b57"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "1de4c57b415e8ca0e023e0009429c3a1d57b0489bb653ce14097ab9f9af09c1d"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7a4d7e94e6f7476091d002395c6f9b26c1dd418"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "70ab72187df10009a845188205e7158386e0715c05554c834e0eeaea2928e0ce"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "aarch64"
git-tree-sha1 = "df3ad8c3e1ba7a01afa3d2a2e2f29302a648d38c"
os = "freebsd"

    [[MLX_C.download]]
    sha256 = "a474f588fe65e522aa3d756a1a97695c9dd84e92e5c7ce7b77f6893bca81b744"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.aarch64-unknown-freebsd.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cf8e96db4a150330e09ed907c50c8d39a8bd09c"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "b6353267de7c979938969abf3a82bd1a21b56fcc51c51e6e32ce47929c671a6c"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9017a1b5634a90a2a37791c5f3c0d3260172ce94"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "6155e384cb336b4cf54b3b04b5396872f032dc21ba10c5344924bc553d341102"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc0a7248ef9b49d68130cd58fdbbec0de6278115"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "18f100b0fe54918edbccdb51a3ff20d7ac5a4c33195bc5ec4e4f02dd0036d5c1"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12f944b328e3e65e83590e2f45c88015c2f7beb4"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "7657a483f41969d2c7ba06dd5727c513f9dd38f4e923c1e7cb160ce5a0181f5b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c6ac3f075ebc7e42a0cb3d60bc52c2c6a91d715"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "59115d3db24cb5b11f40f60fc15e3b5644f552c1ddccdc808f27d25bc8cbda2e"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c53a64d022819838219cf26f8a5502e0de1893de"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "08ff04b5568939209c1ceacfe5dc0c58a75210c511e53d91f44669460e6e99b5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b467df93aaf7e1a6d346450dd355bce6ab830a26"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "21e8bd81c6c8e86b857a81b0a26e453767e67fd7da8dafa6f67b322d199327a3"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLX_C]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7fae90e0f3ecfbf91ad8d0d46d8b061c42ea4c4"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d0c53e07ecb2c4f6892bb14eddecd065c2834a420c03c2c7844cfac36fedd78f"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32f773cd82b8dc2b936403159a4866bac5523bad"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "f70bf706da7518d21322d3efbb8ac400f04c7f47c68db93d5fb5994e635cb0de"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a67db830cfac07d8ef7e578460b22375cbde48a"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "a688a9c411d7f2e3c9b826840c8b19e80cd082cf2b103f9204fdbb142cc265c9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaea3557029266d4009b747e1325d551d167924e"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "d548a6e257ccf483ea501676814e2cdaa890af9cb5f5397108c51bc810140dcd"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bd7d17413ce7937fda9c277bc9e98a26b913e2e"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "c69d8f04ff4a28c352297bcd3be465b5a8ceb9ef44fa3081f5237e21082ddd12"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4c5c2810a36ffdbd934f7ee523c3d32d801b885"
os = "windows"

    [[MLX_C.download]]
    sha256 = "89b42e3084a6f557e32760b3d91acf61adf5a100d3369c17783b4cec98d4f327"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLX_C]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "242d7f6dba7fa0cc982e25d82951fcf3ecde765d"
os = "windows"

    [[MLX_C.download]]
    sha256 = "fb79dbd62169ad5d2b0b12c3fc0cd940f932583ef0266c822f5a5ce24037f783"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLX_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72b01d44bd98000369c58126ac5c0ff2503321de"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "c109f9ee395175faf7d7029294a7747e8962591eaee88cc3f5162ae6c526365b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "093bd86619e5db46f448594921f3cde1125194c3"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "967ce076d35903f3444685eb962fc189304e0f70bf2118434dd0f6ea4c6eba41"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71e7d528bc814a7f44d5eb75fe53b696f06915fc"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "2f36e9e7dada2dad1cb374fe245f9adb06cb35fe6c44ff0c187d9562e97886bd"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.riscv64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdfba5c89399f1d380c794ed631322dbed400d90"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "4e8216b529cab2d5fbeccdb94661e5ada477cc3be39a90089f73d85c3b728644"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.riscv64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
git-tree-sha1 = "0a2e60febc576770d8c81d40f4fd284730882806"
os = "macos"

    [[MLX_C.download]]
    sha256 = "606f80f33342be81823bb5b9d4c641f22d0d930bb7b11b2863b6059867b92be9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-apple-darwin.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb2840e01475f355b3b58d62b1b254ac1095fba1"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "dd82362b02a1fa92b3d87b111bd47af697e8dac714181edb12ae80e563b2a2d9"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f292b5bff7798132e89e3fa418c644493826c984"
libc = "glibc"
os = "linux"

    [[MLX_C.download]]
    sha256 = "0c4235d69c17ddf0e753acbfa3d61df9480ce062dcec0f6bc0cc75b42b4bc250"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b547dcd225873f1cdcfee27e601b7adc8a14ab1"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "9fed6e38691cc844d6849ffb10b314c3d0585ffc85abfba2937adb7cc2ebc3d5"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7044b014ff659cd6d39187abd6a1e59500b8695e"
libc = "musl"
os = "linux"

    [[MLX_C.download]]
    sha256 = "3329ca760bad6a56f0f601dedc33b12c2f07ef9f4a2aafda84b9ccc73998d5a0"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLX_C]]
arch = "x86_64"
git-tree-sha1 = "73fda34515c2db1c17f7a7042e08587a3f12f3b2"
os = "freebsd"

    [[MLX_C.download]]
    sha256 = "8002b2fc78349eda0eb6a94103ad92a73b792f2838c1f355eaf5321d7127ccef"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4bc1a1a0e1c440ad5c0c10cbe89c842228e7705"
os = "windows"

    [[MLX_C.download]]
    sha256 = "ef59c5c532e8f966e7a3b449d6bcdd4d14eb997732baa25ee3dc992e2bcbec62"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLX_C]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95ac72b87052c397423489abe9275efa7caa0502"
os = "windows"

    [[MLX_C.download]]
    sha256 = "7c9e6d84a1455b62eed012cac09a03dd5e2be0228e6d5c51093e4f12df82f27b"
    url = "https://github.com/JuliaBinaryWrappers/MLX_C_jll.jl/releases/download/MLX_C-v0.2.0+0/MLX_C.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
